config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"

  resources :empruntables, only: [:index] do
    resources 'emprunts', only: [:new, :create]
  end
  resources 'emprunts', only: [:index]
  root 'empruntables#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emprunt.rb
class Emprunt < ApplicationRecord
  belongs_to :empruntable
  validates :email, format: { with: /.+@.+\.\w+/ }, presence: true
  validates :date_emprunt, presence: true
  validates :date_restitution, presence: true
end

app/models/empruntable.rb
class Empruntable < ApplicationRecord
  has_one_attached :photo
  has_many :emprunts

  def to_param
    "#{id}-#{nom.parameterize}"
  end

  def non_disponible
    emprunts.flat_map{|emprunt| (emprunt.date_emprunt..emprunt.date_restitution).to_a.map{|d| d.strftime('%m/%d/%Y')}}
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/empruntables_controller.rb
class EmpruntablesController < ApplicationController
  before_action :set_empruntable, only: [:show, :edit, :update, :destroy]

  def index
    @empruntables = Empruntable.all
  end
end

app/controllers/emprunts_controller.rb
class EmpruntsController < ApplicationController
  before_action :require_login, only: :index

  def new
    @empruntable = Empruntable.find(params[:empruntable_id])
    @emprunt = Emprunt.new
    gon.dates_non_disponibles = @empruntable.non_disponible
  end

  def create
    @empruntable = Empruntable.find(params[:empruntable_id])
    @emprunt = Emprunt.new(emprunt_params)
    @emprunt.empruntable = @empruntable
    if @emprunt.save
      UserMailer.with(emprunt: @emprunt).confirmation.deliver_later
      redirect_to new_empruntable_emprunt_path(@empruntable), notice: "Nous venons de vous envoyer un mail de confirmation"
    else
      gon.dates_non_disponibles = @empruntable.non_disponible
      render :new
    end
  end

  def index
    @emprunts = Emprunt.all
  end

  private

  def emprunt_params
    params.require(:emprunt).permit(:nom, :prenom, :tel, :email, :date_emprunt, :date_restitution)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empruntables_helper.rb
module EmpruntablesHelper
end

app/views/empruntables/_form.html.haml
= form_with(model: empruntable, local: true) do |form|
  - if empruntable.errors.any?
    #error_explanation
      %h2
        = pluralize(empruntable.errors.count, "error")
        prohibited this empruntable from being saved:
      %ul
        - empruntable.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :nom
    = form.text_field :nom
  .field
    = form.label :description_courte
    = form.text_field :description_courte
  .field
    = form.label :description_longue
    = form.text_field :description_longue
  .actions
    = form.submit

app/views/empruntables/edit.html.haml
%h1 Editing Empruntable
= render 'form', empruntable: @empruntable
= link_to 'Show', @empruntable
|
= link_to 'Back', empruntables_path

app/views/empruntables/index.html.haml
.bg-indigo-900
  .flex.items-start.flex-wrap.justify-between.mx-10.md:mx-40.pb-10
    %div{:class => "lg:w-1/2"}
      %h1.text-white.text-2xl.md:text-5xl.font-bold.leading-tight.mb-8
        Réservez une salle, empruntez du matériel avec
        %span{:style => "color: lightgreen"} ResaDon
      %p.text-indigo-200.md:text-xl Grâce au village de Châteldon, vous pouvez réserver en ligne des salles pour vos événements, connaître leurs disponibilités, emprunter du matériel !
    .hidden.lg:block{:class => "lg:w-1/2"}
      = image_tag('booking.svg', alt: 'Illustration calendrier')
.bg-gray-200.py-20
  .mx-10.md:mx-40
    %h2.text-2xl.font-bold.mb-10.border-b.border-gray-400.pb-4
      Ce que vous pouvez réserver
    .flex.items-start.flex-wrap.justify-center
      - @empruntables.each do |empruntable|
        .max-w-sm.rounded-lg.overflow-hidden.shadow-lg.my-10.mx-10
          = image_tag(url_for(empruntable.photo), alt: empruntable.nom, class: "w-full object-cover h-64")
          .px-6.py-4
            .font-bold.text-xl.mb-2= empruntable.nom
            %p.text-base.text-gray-700= empruntable.description_courte
          .px-6.py-4
            = link_to('Demander une réservation', new_empruntable_emprunt_path(empruntable), class: "no-underline block font-bold text-center rounded bg-indigo-900 text-white px-4 py-3 hover:bg-indigo-800 outline-none focus:shadow-outline transition ease-in-out duration-150")

app/views/empruntables/new.html.haml
%h1 New Empruntable
= render 'form', empruntable: @empruntable
= link_to 'Back', empruntables_path

app/views/emprunts/_calendar_input.html.haml
%datepicker{":disabled-dates" => "disabledDates", ":language" => "fr", "calendar-class" => "bg-white mt-12 rounded-lg shadow p-4 absolute top-0 left-0 z-40", :format => "dd/MM/yyyy", "input-class" => "bg-gray-400 appearance-none border-2 border-gray-400 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-indigo-900", "monday-first" => "", :name => input_name, :placeholder => "Choisir une date"}

app/views/emprunts/index.html.haml
.bg-gray-200.py-20.px-40
  %div
    %h2.text-2xl.font-bold.mb-10.border-b.border-gray-400.pb-4
      Réservations
    %table.table-audo
      %thead
        %tr
          %th.px-4.py-2
          %th.px-4.py-2 Date d'emprunt
          %th.px-4.py-2 Date de restitution
          %th.px-4.py-2 Nom
          %th.px-4.py-2 Prénom
          %th.px-4.py-2 Email
          %th.px-4.py-2 Tel
      %tbody
        - @emprunts.each do |emprunt|
          %tr
            %td.border.px-4.py-2= emprunt.empruntable.nom
            %td.border.px-4.py-2= emprunt.date_emprunt
            %td.border.px-4.py-2= emprunt.date_restitution
            %td.border.px-4.py-2= emprunt.nom
            %td.border.px-4.py-2= emprunt.prenom
            %td.border.px-4.py-2= emprunt.email
            %td.border.px-4.py-2= emprunt.tel

app/views/emprunts/new.html.haml
- content_for :head do
  = javascript_pack_tag 'calendar_vue', 'data-turbolinks-track': 'reload'

- if flash[:notice]
  .bg-teal-100.border-t-4.border-teal-500.rounded-b.text-teal-900.text-center.px-4.py-3.shadow-md{:role => "alert"}
    %p.text-xl.font-bold Succès
    %p= flash[:notice]
- if @emprunt.errors.any?
  .bg-red-100.border-t-4.border-red-500.rounded-b.text-red-900.text-center.px-4.py-3.shadow-md{:role => "alert"}
    %p.text-xl.font-bold L'emprunt n'est pas valide
    %ul
      - @emprunt.errors.full_messages.each do |msg|
        %li= msg
.bg-gray-200.px-10.md:px-40.py-10
  .flex.items-center.flex-wrap
    .pr-10{:class => "xl:w-1/2"}
      %h1.text-4xl.font-bold.pb-5= @empruntable.nom
      %p.text-base= @empruntable.description_courte
      .py-5
        = image_tag(url_for(@empruntable.photo), alt: @empruntable.nom, class: 'w-full rounded-lg overflow-hidden')
    %div#calendar{:class => "xl:w-1/2"}
      .p-10.border.rounded-lg.xl:shadow-xl.flex.flex-col.items-center
        .pb-10.text-center.text-2xl.font-bold Quand souhaitez-vous réserver ?
        = form_with model: [:empruntable, @emprunt], local: true, class: 'w-full' do |f|
          .flex.items-center.mb-6
            %div{:class => "w-1/3"}
              = f.label :prenom, class: "block text-gray-500 font-bold text-right pr-4"
            %div{:class => "w-2/3"}
              = f.text_field :prenom, class: " bg-gray-400 appearance-none border-2 border-gray-400 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-indigo-900"
          .flex.items-center.mb-6
            %div{:class => "w-1/3"}
              = f.label :nom, class: "block text-gray-500 font-bold text-right pr-4"
            %div{:class => "w-2/3"}
              = f.text_field :nom, class: " bg-gray-400 appearance-none border-2 border-gray-400 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-indigo-900"
          .flex.items-center.mb-6
            %div{:class => "w-1/3"}
              = f.label :email, class: "block text-gray-500 font-bold text-right pr-4"
            %div{:class => "w-2/3"}
              = f.text_field :email, class: " bg-gray-400 appearance-none border-2 border-gray-400 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-indigo-900"
          .flex.items-center.mb-6
            %div{:class => "w-1/3"}
              = f.label :tel, class: "block text-gray-500 font-bold text-right pr-4"
            %div{:class => "w-2/3"}
              = f.text_field :tel, class: " bg-gray-400 appearance-none border-2 border-gray-400 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-indigo-900"
          .flex.items-center.mb-6
            %div{:class => "w-1/3"}
              = label_tag "Date d'emprunt", nil, class: "block text-gray-500 font-bold text-right pr-4"
            %div{:class => "w-2/3"}
              = render partial: 'calendar_input', locals: { input_name: "emprunt[date_emprunt]" }
          .flex.items-center.mb-6
            %div{:class => "w-1/3"}
              = label_tag "Date de restitution", nil, class: "block text-gray-500 font-bold text-right pr-4"
            %div{:class => "w-2/3"}
              = render partial: 'calendar_input', locals: { input_name: "emprunt[date_restitution]" }
          .md:flex.md:items-center
            %div{:class => "md:w-1/3"}
            .mt-10{:class => "md:w-2/3"}
              = f.submit 'Demander une réservation', class: "w-full shadow bg-green-500 hover:bg-indigo-800 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded-lg"
  %h2.text-2xl.font-bold.mt-10.border-b.border-gray-400.pb-4
    Conditions de réservation

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: "viewport", :content => "width=device-width, initial-scale=1.0"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Resadon
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = yield :head
  %body
    = Gon::Base.render_data
    .bg-indigo-900
      %nav.flex.items-center.justify-between.p-10
        = link_to root_path do
          .flex.items-center
            = image_tag("blason-chateldon-small.png", alt: 'Blason Chateldon', class: 'px-5')
            .text-base.text-white.tracking-wider ResaDon
        - if signed_in?
          .flex.items-end
            = link_to 'Reservations', emprunts_path, class: 'text-white mx-8'
            = link_to 'Se déconnecter', sign_out_path, method: :delete, class: "text-white"
        - else
          = link_to 'Accès réservé', sign_in_path, class: "text-white"

    - if flash[:notice]
      .bg-teal-100.border-t-4.border-teal-500.rounded-b.text-teal-900.text-center.px-4.py-3.shadow-md{:role => "alert"}
        %p.text-xl.font-bold Succès
        %p= flash[:notice]
    = yield

app/views/layouts/authentication.html.haml
!!!
%html
  %head
    %meta{name: "viewport", :content => "width=device-width, initial-scale=1.0"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Resadon
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = yield :head
  %body.h-screen.overflow-hidden.flex.flex-col.justify-center.bg-gray-200
    = link_to "Retour à l'accueil", root_path, class: 'text-base text-gray-700 mx-auto mb-4'
    - flash.each do |key, value|
      .bg-gray-200.border-t-4.border-red-600.text-red-600.text-center.px-4.py-3.shadow-md.rounded-b.mx-auto
        %p.font-bold Attention !
        %p= value

    .container.mx-auto
      .flex.flex-row.justify-center.px-6.my-12
        .w-full.flex{:class => "lg:w-11/12"}
          .w-full.bg-gray-400.hidden.lg:block.bg-cover.rounded-l-lg{:class => "lg:w-1/2", :style => "background-image: url(#{image_path('maison.jpg')})"}
          .w-full.bg-white.p-10.rounded-lg.lg:rounded-l-none{:class => "lg:w-1/2"}
            = yield

app/views/users/_form.html.haml
.text-field
  = form.label :email
  = form.text_field :email, type: 'email'
.password-field
  = form.label :password
  = form.password_field :password

app/views/users/index.html.haml
.bg-indigo-900
  %a{:href => "#"}
    .p-10.flex.items-center
      = image_tag("blason-chateldon-small.png", alt: 'Blason Chateldon', class: 'px-5')
      .text-base.text-white.tracking-wider ResaDon
  .flex.items-start.flex-wrap.justify-between.mx-40.pb-10
    %div{:class => "lg:w-1/2"}
      %h1.text-white.text-2xl.md:text-5xl.font-bold.leading-tight.mb-8
        Réservez une salle, empruntez du matériel avec
        %span{:style => "color: lightgreen"} ResaDon
      %p.text-indigo-200.md:text-xl Grâce au village de Châteldon, vous pouvez réserver en ligne des salles pour vos événements, connaître leurs disponibilités, emprunter du matériel !
    .hidden.lg:block{:class => "lg:w-1/2"}
      = image_tag('booking.svg', alt: 'Illustration calendrier')
.bg-gray-200.py-20.px-40
  %div
    %h2.text-2xl.font-bold.mb-10.border-b.border-gray-400.pb-4
      Ce que vous pouvez réserver
    .flex.items-start.flex-wrap.justify-between
      .max-w-sm.rounded-lg.overflow-hidden.shadow-lg.my-10.mx-5
        = image_tag("salle-polyvalente.jpg", alt: "salle polyvalente", class: "w-full h-64")
        .px-6.py-4
          .font-bold.text-xl.mb-2 Salle polyvalente
          %p.text-base.text-gray-700 Capacité de 100 personnes
        .px-6.py-4
          %a.no-underline.block.font-bold.text-center.rounded.bg-indigo-900.text-white.px-4.py-3.hover:bg-indigo-800.outline-none.focus:shadow-outline.transition.ease-in-out.duration-150{:href => "/article.html"} Réserver
      .max-w-sm.rounded-lg.overflow-hidden.shadow-lg.my-10.mx-5
        = image_tag("salle-2.jpg", alt: "salle polyvalente", class: "w-full h-64")
        .px-6.py-4
          .font-bold.text-xl.mb-2 Grande salle polyvalente
          %p.text-base.text-gray-700 Capacité de 200 personnes
        .px-6.py-4
          %a.no-underline.block.font-bold.text-center.rounded.bg-indigo-900.text-white.px-4.py-3.hover:bg-indigo-800.outline-none.focus:shadow-outline.transition.ease-in-out.duration-150{:href => "#"} Réserver
      .max-w-sm.rounded-lg.overflow-hidden.shadow-lg.my-10.mx-5
        = image_tag("barriere.jpg", alt: "barriere", class: "w-full h-64")
        .px-6.py-4
          .font-bold.text-xl.mb-2 Barriere
          %p.text-base.text-gray-700 5m de longueur
        .px-6.py-4
          %a.no-underline.block.font-bold.text-center.rounded.bg-indigo-900.text-white.px-4.py-3.hover:bg-indigo-800.outline-none.focus:shadow-outline.transition.ease-in-out.duration-150{:href => "#"} Réserver
      .max-w-sm.rounded-lg.overflow-hidden.shadow-lg.my-10.mx-5
        = image_tag("salle-2.jpg", alt: "salle polyvalente", class: "w-full h-64")
        .px-6.py-4
          .font-bold.text-xl.mb-2 Salle polyvalente
          %p.text-base.text-gray-700 Capacité de 100 personnes
        .px-6.py-4
          %a.no-underline.block.font-bold.text-center.rounded.bg-indigo-900.text-white.px-4.py-3.hover:bg-indigo-800.outline-none.focus:shadow-outline.transition.ease-in-out.duration-150{:href => "#"} Réserver

app/views/users/new.html.haml
#clearance.sign-up
  %h2= t(".title")
  = form_for @user do |form|
    = render partial: '/users/form', object: form
    .submit-field
      = form.submit
    .other-links
      = link_to t(".sign_in"), sign_in_path